const {
  acceptTradeRequest,
  cancelArenaTradeListing,
  cancelTradeRequest,
  cancelTradeSession,
  confirmTrade,
  createArenaTradeListing,
  denyTradeRequest,
  getArenaTradeListings,
  getIncomingTradeRequests,
  getMyArenaTradeListings,
  getTradeSession,
  offerCardInTrade,
  offerCoinInTrade,
  removeCardFromTrade,
  removeCoinFromTrade,
  searchArenaTradeCards,
  searchArenaUsers,
  sendTradeRequest,
  unconfirmTrade,
} = require("./legacy-service");

module.exports = {
  acceptTradeRequest,
  cancelArenaTradeListing,
  cancelTradeRequest,
  cancelTradeSession,
  confirmTrade,
  createArenaTradeListing,
  denyTradeRequest,
  getArenaTradeListings,
  getIncomingTradeRequests,
  getMyArenaTradeListings,
  getTradeSession,
  offerCardInTrade,
  offerCoinInTrade,
  removeCardFromTrade,
  removeCoinFromTrade,
  searchArenaTradeCards,
  searchArenaUsers,
  sendTradeRequest,
  unconfirmTrade,
};
